### ISSUE TITLE
Falsy terminal option registers invalid command on Windows

### ISSUE THREAD

**Issue by rfricz** [Shubham-Kumar-2000/protocol-registry#13] opened 2021-06-05 12:19 UTC
### **Describe the bug:**
When on Windows with Node 14 LTS, calling the `register` function with the `terminal` option set to `false` or `undefined` results in an invalid command being registered – the problem is in the following line:
```js
(terminal && 'cmd /k ') + command
```
which produces commands that start with "false" or "undefined". Replacing it with 
```js
(terminal ? 'cmd /k ' : '') + command
```
makes the command work.

### **To Reproduce:**
Step through the usage example with a debugger, pass `false` for the terminal option:
```js
ProtocolRegistry.register({
    protocol: 'testproto', // sets protocol for your command , testproto://**
    command: `node ${path.join(__dirname, './tester.js')} $_URL_`, // this will be executed with a extra argument %url from which it was initiated
    override: true, // Use this with caution as it will destroy all previous Registrations on this protocol
    terminal: false, // Use this to run your command inside a terminal
    script: false
}).then(async () => {
    console.log('Successfully registered');
});
```

### **Expected behavior:**

Passing `false` for the terminal option should register a correct command.

**Comment by Shubham-Kumar-2000** [comment] 2021-06-05 13:10
Confirmed bug

**Comment by Shubham-Kumar-2000** [comment] 2021-06-05 13:12
Hi @rfricz it will be great if you can raise a pr against this.

**Comment by Shubham-Kumar-2000** [comment] 2021-06-05 13:56
Fixed with commit: c8e1f04055e6f7a481c1ac61eeee60b7211ec7b1
New npm version published

**Closed by Shubham-Kumar-2000** 2021-06-05 13:56 UTC
Labels: bug

**Comment by rfricz** [comment] 2021-06-05 17:13
Thanks for fixing this so quickly!

**Comment by Shubham-Kumar-2000** [comment] 2021-06-05 17:42
Its my pleasure.
May be because its my first npm module
